### ISSUE TITLE
UnhandledRejection TypeError: Do not know how to serialize a BigInt

### ISSUE THREAD

**Issue by eric8810** [keichi/binary-parser#137]
JSON.stringfy not capable with bigInt data(uint64) while using babel loader.
looks like we should use toString() in this case.

error:

11:04:17.184 › {
  constructor: 'TypeError',
  name: 'UnhandledRejection TypeError',
  stack: 'UnhandledRejection TypeError: Do not know how to serialize a BigInt\n' +
    '    at JSON.stringify (<anonymous>)\n' +
    '    at toJSON (/Users/chenghan/code/chat/node_modules/electron-log/src/transform/object.js:132:26)\n' +
    '    at /Users/chenghan/code/chat/node_modules/electron-log/src/transform/index.js:43:12\n' +
    '    at Array.reduce (<anonymous>)\n' +
    '    at Object.transform (/Users/chenghan/code/chat/node_modules/electron-log/src/transform/index.js:42:23)\n' +
    '    at transport (/Users/chenghan/code/chat/node_modules/electron-log/src/transports/console.js:45:35)\n' +
    '    at runTransport (/Users/chenghan/code/chat/node_modules/electron-log/src/log.js:43:5)\n' +
    '    at runTransports (/Users/chenghan/code/chat/node_modules/electron-log/src/log.js:26:7)\n' +
    '    at log (/Users/chenghan/code/chat/node_modules/electron-log/src/log.js:20:3)\n' +
    '    at Object._callee5$ (webpack:///./src/main/controller/messageControll.js?:413:23)'
}

refer:

toObject() {
        return JSON.parse(JSON.stringify(this, (key, value) =>
            typeof value === 'bigint'
                ? value.toString()
                : value // return everything else unchanged
        ));
    }

**Comment by eric8810** [comment]
na，case by something else, ignore me
