### ISSUE TITLE
Recursive parser definition crashes at compilation

### ISSUE THREAD

**Issue by oparisy** [keichi/binary-parser#23]
I am using `binary-parser` to write a parser for a tree-like file format: it is composed of "nodes" which are followed by children. Those children themselves are nodes.

My parser definition boils down to:

``` javascript
var Parser = require('binary-parser').Parser;

var nodeParser = new Parser();

// (Some fields definition here)

nodeParser.array('nestedList', {
    type: nodeParser,
    readUntil: function(item, buffer) {
        // (An actual ending condition here)
        return true;
    }
});

console.log(nodeParser.getCode());
```

But executing this code leads to a recursion error:

```
pwd>node crash.js
pwd\node_modules\binary-parser\lib\context.js:87
    var params = Array.prototype.slice.call(arguments, 1);
                                       ^

RangeError: Maximum call stack size exceeded
    at Context.interpolate (pwd\node_modules\binary-parser\lib\context.js:87:40)
    at Context.pushCode (pwd\node_modules\binary-parser\lib\context.js:61:38)
    at Parser.generateArray (pwd\node_modules\binary-parser\lib\binary_parser.js:474:13)
    at Parser.generate (pwd\node_modules\binary-parser\lib\binary_parser.js:295:37)
    at Parser.generateNext (pwd\node_modules\binary-parser\lib\binary_parser.js:334:25)
    at Parser.generate (pwd\node_modules\binary-parser\lib\binary_parser.js:304:17)
    at Parser.generateArray (pwd\node_modules\binary-parser\lib\binary_parser.js:491:14)
    at Parser.generate (pwd\node_modules\binary-parser\lib\binary_parser.js:295:37)
    at Parser.generateNext (pwd\node_modules\binary-parser\lib\binary_parser.js:334:25)
    at Parser.generate (pwd\node_modules\binary-parser\lib\binary_parser.js:304:17)
```

Is `binary-parse` able to express such recursive parser definitions? If so, how should I define it?

Regards.

**Comment by shamansir** [comment]
Probably you need to create your parser instances using a factory function, like: 

```javascript
function createNodeParser() {
    return new Parser()
        // fields definition
        nodeParser.array('nestedList', {
            type: createNodeParser(),
            readUntil: function(item, buffer) {
                // (An actual ending condition here)
                return true;
        }
    });
} 
```

Though it would be able to re-use the same instance for going deeper into trees.

**Comment by shamansir** [comment]
Uh, no, this code is obviously not working either, since functions call themselves recursively:

```javascript
const Parser = require('binary-parser').Parser;

var finishTreeParser = new Parser();

function createNestedParser() {
    return new Parser()
        .int8('goDeeper')
        .choice('deep', {
            tag: 'goDeeper',
            choices: {
                1: createNestedParser(),
                0: finishTreeParser
            }
        })
};

console.log(createNestedParser().parse(new Buffer('1110', 'hex')));
```

**Comment by shamansir** [comment]
I've implemented the ability to go into recursion to parse trees of the same node type in PR #41

**Comment by oparisy** [comment]
I'm taking the liberty to close this issue now that #41 has been merged. Thanks for your work @shamansir!
